### ISSUE TITLE
Mix Task fails without single root tag

### ISSUE THREAD

**Issue by mikehostetler** [mhanberg/temple#34]
**Describe the bug**
When attempting to use `mix temple.convert` to translate an existing HTML file into Temple syntax, the conversion fails without a single root HTML tag.

_File 1_
```
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>
    does not compromise speed or maintainability.</p>
</section>
```

_File 2_
```
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>
    does not compromise speed or maintainability.</p>
</section>
<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
    </ul>
  </article>
</section>
```

**To Reproduce**
1. Attempting to run `mix temple.convert` on _File 2_ above fails

**Expected behavior**
Temple syntax should be reported to StdOut

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.15.1  Catalina
 - Temple Version: `master` (0.4.1)
 - Elixir Version: 1.9.1
 - Erlang Version: 22

**Error**
```
% cat apps/gf_web/lib/gf_web/templates/page/index.html.eex | mix temple.convert
** (FunctionClauseError) no function clause matching in Temple.HtmlToTemple.do_parse/2

    The following arguments were given to Temple.HtmlToTemple.do_parse/2:

        # 1
        [{"section", [{"class", "phx-hero"}], [{"h1", [], ["<%= gettext \"Welcome to %{name}!\", name: \"Phoenix\" %>"]}, {"p", [], ["A productive web framework that", {"br", [], []}, "\n    does not compromise speed or maintainability."]}]}, {"section", [{"class", "row"}], [{"article", [{"class", "column"}], [{"h2", [], ["Resources"]}, {"ul", [], [{"li", [], [{"a", [{"href", "https://hexdocs.pm/phoenix/overview.html"}], ["Guides & Docs"]}]}, {"li", [], [{"a", [{"href", "https://github.com/phoenixframework/phoenix"}], ["Source"]}]}, {"li", [], [{"a", [{"href", "https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md"}], ["v1.4 Changelog"]}]}]}]}, {"article", [{"class", "column"}], [{"h2", [], ["Help"]}, {"ul", [], [{"li", [], [{"a", [{"href", "https://elixirforum.com/c/phoenix-forum"}], ["Forum"]}]}, {"li", [], [{"a", [{"href", "https://webchat.freenode.net/?channels=elixir-lang"}], ["#elixir-lang on Freenode IRC"]}]}, {"li", [], [{"a", [{"href", "https://twitter.com/elixirphoenix"}], ["Twitter @elixirphoenix"]}]}]}]}]}]

        # 2
        0

    Attempted function clauses (showing 5 out of 5):

        def do_parse({tag, [], []}, indent)
        def do_parse({tag, attrs, []}, indent)
        def do_parse({tag, attrs, [""]}, indent)
        def do_parse({tag, attrs, children}, indent)
        def do_parse(text, indent) when is_binary(text)

    lib/temple/html_to_temple.ex:16: Temple.HtmlToTemple.do_parse/2
    lib/temple/html_to_temple.ex:11: Temple.HtmlToTemple.parse/1
    lib/mix/tasks/temple.convert.ex:19: Mix.Tasks.Temple.Convert.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

**Comment by mhanberg** [comment]
@mikehostetler Thanks for the bug report.

I will look into this, but at first glance I am wondering if it is failing because you are parsing an `eex` file and not vanilla html. The mix task is not designed for converting EEx to Temple, only vanilla html.

In the mean time, are you attempting to bootstrap a new app with Temple? You can use the layout generator to generate the Temple version of the layout file which will get you most of the way there. `mix temple.gen.layout`

**Comment by mhanberg** [comment]
@mikehostetler Please upgrade to v0.4.2 for the fix.
